name: Gatsby Publish

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-10
    steps:
      - uses: action/checkout@v2
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
    access-token: ${{ secrets.ACCESS_TOKEN }}
    deploy-branch: gh-pages
    gatsby-args: --prefix-paths